language: python
cache: pip

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run pytest
script: pytest tests

notifications:
  email: false
