language: python
cache: pip

matrix:
  include:
    - python: "3.5"
      dist: trusty
      sudo: false
    - python: "3.6"
      dist: trusty
      sudo: false
    - python: "3.7"
      dist: xenial
      sudo: false

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run pytest
script: pytest tests

notifications:
  email: false
